#!/bin/sh

set -e

lb config noauto \
        --distribution bookworm \
	--bootloaders "grub-efi" \
	--apt-recommends false \
	--bootappend-live "boot=live noeject quiet splash" \
	--chroot-squashfs-compression-type zstd \
	"${@}"
